on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  GO_VERSION: '1.21'
jobs:
  Dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          verbose: true
  Go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: test with coverage
        run: go test -coverprofile=coverage.txt --covermode=atomic
      - name: Check go mod
        run: |
          go mod tidy
          git diff --exit-code go.mod
      - name: lint
        uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: latest
          # skip cache because of flaky behaviors
          skip-build-cache: true
          skip-pkg-cache: true
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  Publishing:
    runs-on: ubuntu-latest
    needs:
      - Dockerfile
      - Go
    steps:
      - uses: actions/checkout@v3
      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE }}
          registry: ghcr.io/${{ github.repository_owner }}
      - name: podman build
        run: |
          podman build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .
      - name: podman push
        run: |
          podman push ghcr.io/${{ github.repository }}:${{ github.sha }}
